"""create vehicles permissions and access events

Revision ID: 285c86e13beb
Revises: dda2992a9d8b
Create Date: 2026-09-23 00:21:15.978183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285c86e13beb'
down_revision: Union[str, Sequence[str], None] = 'dda2992a9d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('access_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('detected_plate', sa.String(length=20), nullable=True),
    sa.Column('face_score', sa.Float(), nullable=True),
    sa.Column('plate_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('evidence_key', sa.String(length=255), nullable=True),
    sa.CheckConstraint("decision IN ('AUTHORIZED', 'REJECTED', 'REVIEW')", name='ck_access_events_decision'),
    sa.CheckConstraint("event_type IN ('ENTRY', 'EXIT')", name='ck_access_events_type'),
    sa.CheckConstraint('face_score IS NULL OR (face_score >= 0 AND face_score <= 1)', name='ck_access_events_face_score'),
    sa.CheckConstraint('plate_score IS NULL OR (plate_score >= 0 AND plate_score <= 1)', name='ck_access_events_plate_score'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_events_detected_plate'), 'access_events', ['detected_plate'], unique=False)
    op.create_index(op.f('ix_access_events_timestamp'), 'access_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_access_events_user_id'), 'access_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_access_events_vehicle_id'), 'access_events', ['vehicle_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name='ck_permissions_valid_period'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vehicle_id', name='uq_permissions_user_vehicle')
    )
    op.create_index(op.f('ix_permissions_user_id'), 'permissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_permissions_vehicle_id'), 'permissions', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_vehicle_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_user_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_access_events_vehicle_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_user_id'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_timestamp'), table_name='access_events')
    op.drop_index(op.f('ix_access_events_detected_plate'), table_name='access_events')
    op.drop_table('access_events')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
